services:
  - type: web
    name: campus-sync-backend
    env: docker
    plan: free
    rootDir: campus-sync-java-restapi
    envVars:
      - key: PORT
        value: 8091
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: campus-sync-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: campus-sync-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: campus-sync-db
          property: password
      - key: ALLOWED_ORIGINS
        value: "*" # Initially permit all, we will secure this with Vercel's URL once frontend is deployed

databases:
  - name: campus-sync-db
    databaseName: campus_sync_db
    user: postgres
    plan: free
